from utils.encoders.sam import SAMPolicy
from utils.encoders.mvp import MVPPolicy
from utils.encoders.mae import MAEPolicy
from utils.encoders.dinov2 import DinoV2Policy
from utils.encoders.clip import CLIPPolicy
from utils.encoders.r3m import R3MPolicy
from utils.encoders.vip import VIPPolicy
from utils.encoders.vc1 import VC1Policy
from utils.encoders.mocov3 import MoCoV3Policy
from utils.encoders.ibot import IBOTPolicy
from utils.encoders.obj_rn import ObjRNPolicy